services:
  chronos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chronos
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt:ro
      - ./data/certbot/www:/var/www/certbot:ro
